# Generated by Django 4.0.4 on 2022-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(max_length=300, verbose_name='Условия хранения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.TextField(verbose_name='Пищевая ценность'),
        ),
    ]
